site_name: Playing with code
theme:
    name: material
    custom_dir: mkdocs-material/material
    palette:
        primary: black
    logo: haqreu-plate.png
    features:
        - content.code.copy
        - content.code.annotate

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        check_paths: true
        base_path:
            - docs/deranged/
            - docs/compiler/
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences


#    - admonition
#    - pymdownx.details
#    - pymdownx.superfences
#    - attr_list


extra_javascript:
#    - javascripts/mathjax.js
#    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


#repo_url: https://github.com/ssloy

plugins: []

#plugins:
#  - include-markdown

nav:
    - 'index.md'
    - 'tinycompiler':
        - 'compiler/index.md'
    - 'Deranged programmer':
        - 'deranged/cursed-fire.md'

