site_name: Playing with code
site_url: https://ssloy.github.io/
theme:
    name: material
    custom_dir: mkdocs-material/material
    palette:
        primary: black
    logo: haqreu-plate.png
    features:
        - content.code.copy
        - content.code.annotate
        - content.tooltips

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        check_paths: true
        base_path:
            - docs/
            - docs/strange/
            - docs/tinyrenderer/
            - docs/tinycompiler/
            - docs/tinyoptimizer/
            - docs/tinyfloat/
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list

extra_javascript:
#    - javascripts/mathjax.js
#    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#repo_url: https://github.com/ssloy

#use_directory_urls: false
plugins: []

#plugins:
#  - include-markdown

nav:
    - 'Home': 'index.md'
    - 'tinyrenderer':
        - 'tinyrenderer/index.md'
        - 'tinyrenderer/bresenham.md'
        - 'tinyrenderer/rasterization.md'
        - 'tinyrenderer/barycentric.md'
        - 'tinyrenderer/z-buffer.md'
        - 'tinyrenderer/camera-naive.md'
        - 'tinyrenderer/camera.md'
        - 'tinyrenderer/shading.md'
        - 'tinyrenderer/textures.md'
        - 'tinyrenderer/tangent.md'
        - 'tinyrenderer/shadow.md'
        - 'tinyrenderer/ssao.md'
        - 'tinyrenderer/toon.md'
        - 'tinyrenderer/afterword.md'
    - 'tinycompiler':
        - 'tinycompiler/index.md'
        - 'tinycompiler/ast.md'
        - 'tinycompiler/sly.md'
        - 'tinycompiler/symtable.md'
        - 'tinycompiler/display.md'
        - 'tinycompiler/assembly.md'
        - 'tinycompiler/lexer.md'
        - 'tinycompiler/parser.md'
        - 'tinycompiler/afterword.md'
    - 'tinyoptimizer':
        - 'tinyoptimizer/index.md'
        - 'tinyoptimizer/mem2reg.md'
    - 'tinyfloat':
        - 'tinyfloat/index.md'
        - 'tinyfloat/computers-and-numbers.md'
        - 'tinyfloat/print.md'
        - 'tinyfloat/add.md'
    - 'strange things':
        - 'strange/cursed-fire.md'

extra:
    analytics:
        provider: google
        property: G-7F81P6F3D0

