site_name: Playing with code
theme:
  name: material
  custom_dir: mkdocs-material/material
  palette:
    primary: black
  logo: haqreu-plate.png

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

#    - admonition
#    - pymdownx.details
#    - pymdownx.superfences
#    - attr_list


extra_javascript:
#    - javascripts/mathjax.js
#    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


#repo_url: https://github.com/ssloy

plugins: []

#plugins:
#  - include-markdown
